### ISSUE TITLE
Add dashboard icon

### ISSUE THREAD

**Issue by Quossh** [primefaces/primeicons#911] opened 2023-03-28 06:53 UTC
Add "Dashboard" icon as in react icons: https://react-icons.github.io/react-icons/search?q=dashboard (MdOutlineSpaceDashboard)

**Comment by jepsar** [comment] 2023-03-28 07:10
Duplicate of #845

**Comment by onursenture** [comment] 2023-04-17 06:19
Duplicate of #526

**Closed by onursenture** 2023-04-17 06:19 UTC
Labels: duplicate
