### ISSUE TITLE
Velocimeter

### ISSUE THREAD

**Issue by rjcpereira** [primefaces/primeicons#605] opened 2022-02-18 18:52 UTC
![Screenshot 2022-02-18 at 18 50 20](https://user-images.githubusercontent.com/6094989/154744530-e1e2b4bd-6f97-4206-814b-e21371060681.png)

**Comment by onursenture** [comment] 2022-06-11 07:39
Duplicate of #585

**Closed by onursenture** 2022-06-11 07:39 UTC
