### ISSUE TITLE
Add "star-half-fill" icon

### ISSUE THREAD

**Issue by ruskovweb** [primefaces/primeicons#1123] opened 2024-03-14 20:22 UTC
![image](https://github.com/primefaces/primeicons/assets/24957807/7e3e9dc1-6b7f-4135-9289-3fa7e52879ba)

**Comment by jepsar** [comment] 2024-03-15 09:20
Duplicate of #949

**Comment by onursenture** [comment] 2024-03-18 10:41
> Duplicate of #949

+1

**Closed by onursenture** 2024-03-18 10:41 UTC
