### ISSUE TITLE
HeadPhone

### ISSUE THREAD

**Issue by Ahmed-Madher-Alsaeg** [primefaces/primeicons#1060] opened 2023-12-10 08:27 UTC
Please add a headphone icon 

It is very important

**Comment by jepsar** [comment] 2023-12-10 09:21
Duplicate of #91

Adding claims as "It is very important" will not increase its priority. You will be better of searching for existing issues and upvoting them instead of creating duplicates.

**Comment by onursenture** [comment] 2024-03-09 20:05
> Duplicate of #91
> 
> Adding claims as "It is very important" will not increase its priority. You will be better of searching for existing issues and upvoting them instead of creating duplicates.

+1

**Closed by onursenture** 2024-03-09 20:05 UTC
Labels: duplicate
