### ISSUE TITLE
Add "ship" icon 

### ISSUE THREAD

**Issue by marquipaul** [primefaces/primeicons#1127] opened 2024-03-18 13:34 UTC
I would like to request new icon for ship or sea vessel. Thank you

**Comment by jepsar** [comment] 2024-03-18 14:37
Duplicate of #417

**Comment by onursenture** [comment] 2024-03-19 11:54
> Duplicate of #417

+1

**Closed by onursenture** 2024-03-19 11:54 UTC
Labels: duplicate

**Comment by marquipaul** [comment] 2024-03-19 12:16
is it like this pi-ship?
