### ISSUE TITLE
Please add pin icon

### ISSUE THREAD

**Issue by TheMukhtarAhmed** [primefaces/primeicons#809] opened 2022-09-25 20:20 UTC

**Comment by jepsar** [comment] 2023-03-02 15:37
Duplicate of #333

**Closed** 2023-04-14 18:15 UTC
Labels: duplicate

**Comment by inad9300** [comment] 2023-06-19 14:55
@jepsar what expectations should we have with respect to icon requests? They seem to be completely stalled. Should we have any hopes of ever having a bigger icon library in PrimeReact et al.? The current set is pretty limited.

**Comment by jepsar** [comment] 2023-06-19 15:14
I don't know. I'm a PrimeFaces community committer, not a PrimeTek employee. Just helping a hand here by triaging issues.

**Comment by inad9300** [comment] 2023-06-19 15:48
@onursenture how about you? Poor @jepsar is breaking his back here giving his time away for free, it'd be good to make it be worth something :wink:
