### ISSUE TITLE
Add "Snapchat" icon

### ISSUE THREAD

**Issue by jackstruck** [primefaces/primeicons#748] opened 2022-08-25 16:26 UTC
Requesting an icon to represent snap/snapchat. Icons currently exist for apple, google, fb, microsoft. Using the default ghost icon would be ideal. Example here: https://www.vectorstock.com/royalty-free-vector/snapchat-icon-vector-21082479

**Comment by onursenture** [comment] 2022-09-06 11:14
Duplicate of #665

**Closed by onursenture** 2022-09-06 11:14 UTC
