### ISSUE TITLE
add a new GAVEL icon

### ISSUE THREAD

**Issue by guilhermepereiraa95** [primefaces/primeicons#1057] opened 2023-12-04 17:28 UTC
I'm using PrimeIcons but there's no Gavel Icon. Please provide something like a Judge Gavel

**Comment by jepsar** [comment] 2023-12-04 18:48
Duplicate of #609

**Comment by onursenture** [comment] 2024-03-09 19:50
> Duplicate of #609

+1

**Closed by onursenture** 2024-03-09 19:50 UTC
Labels: duplicate
