### ISSUE TITLE
Add "exchange"  icon

### ISSUE THREAD

**Issue by andersonneto** [primefaces/primeicons#456] opened 2021-07-23 11:11 UTC
Please add the exchange icon.
![icon troca](https://user-images.githubusercontent.com/33755367/126773884-ffa73549-2c18-4a0a-9079-a8ad3c71d6ba.png)

**Comment by onursenture** [comment] 2022-09-06 14:32
Duplicate of #575

**Closed by onursenture** 2022-09-06 14:32 UTC
Labels: new icon
