### ISSUE TITLE
add a gender icon

### ISSUE THREAD

**Issue by LuleJayjay** [primefaces/primeicons#998] opened 2023-08-01 10:16 UTC
gender icons are missing.
at least for femal and male would be nice for category filtering for sports tourneys e.g.

**Comment by jepsar** [comment] 2023-08-01 10:19
Duplicate of #206

**Comment by shantaly** [comment] 2023-08-21 08:16
+1 on that

**Comment by jepsar** [comment] 2023-08-21 08:38
> +1 on that

You might want to upvote #206 in that case

**Comment by onursenture** [comment] 2024-03-06 08:50
> Duplicate of #206

+1

**Closed by onursenture** 2024-03-06 08:50 UTC
Labels: duplicate
