### ISSUE TITLE
Add "bank" icon

### ISSUE THREAD

**Issue by snabfinance** [primefaces/primeicons#478] opened 2021-09-14 11:50 UTC

**Comment by onursenture** [comment] 2021-10-21 15:53
Hi, could you please share an example? Thanks,

**Comment by penihel** [comment] 2023-07-31 12:07
just like fontawesome
![image](https://github.com/primefaces/primeicons/assets/1167747/fdfb44be-88d0-46d0-9efd-e887500f1b6e)

**Comment by onursenture** [comment] 2024-03-05 17:34
Duplicate of #668

**Closed by onursenture** 2024-03-05 17:34 UTC
Labels: question
