### ISSUE TITLE
Add "erasor" icon

### ISSUE THREAD

**Issue by SameenaBegumEmerson** [primefaces/primeicons#695] opened 2022-06-22 08:31 UTC
Could we have an icon added for adding sub-group items and as well remove the same
![image](https://user-images.githubusercontent.com/101192517/174982607-2cb7e8d0-9379-4267-a6eb-035fec9278e4.png)

**Comment by onursenture** [comment] 2022-09-06 10:11
Duplicate of #287

**Closed by onursenture** 2022-09-06 10:11 UTC
Labels: duplicate
