### ISSUE TITLE
i need customer support icon

### ISSUE THREAD

**Issue by saqibsattar03** [primefaces/primeicons#960] opened 2023-05-29 07:11 UTC

**Comment by jepsar** [comment] 2023-05-29 07:23
Do you have an example?

**Comment by saqibsattar03** [comment] 2023-06-12 05:34
https://uxwing.com/customer-care-icon
like this one

**Comment by saqibsattar03** [comment] 2023-06-12 05:35
> Do you have an example?

https://uxwing.com/customer-care-icon
like this one

**Comment by onursenture** [comment] 2024-03-05 17:44
Duplicate of #819

**Closed by onursenture** 2024-03-05 17:44 UTC
Labels: duplicate
