### ISSUE TITLE
Add "swap" icon

### ISSUE THREAD

**Issue by Vseslavr** [primefaces/primeicons#335] opened 2021-02-05 16:52 UTC
I am looking for a swap icon for my working project. It would be nice if you add it. Thanks!

**Comment by onursenture** [comment] 2021-02-14 18:52
Hello, can you share a reference icon please?

**Comment by Vseslavr** [comment] 2021-02-14 19:07
Hi! I think something like this (see attached image), but using prime-icon
styling

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вс, 14 февр. 2021 г. в 20:52, Onur Senture <notifications@github.com>:

**Comment by onursenture** [comment] 2021-02-16 14:51
@Vseslavr I cannot see the attachment.

**Comment by Vseslavr** [comment] 2021-02-16 15:38
Hmm... I attach another one. Please, try it.

вт, 16 февр. 2021 г. в 16:51, Onur Senture <notifications@github.com>:

**Comment by onursenture** [comment] 2021-02-16 15:39
@Vseslavr still no visible. Maybe you should try web interface? :)

**Comment by Vseslavr** [comment] 2021-02-16 15:43
Okey =) Let's try this https://ibb.co/G9dLvfY

вт, 16 февр. 2021 г. в 17:39, Onur Senture <notifications@github.com>:

**Comment by melloware** [comment] 2021-02-21 18:44
@onursenture I think you can close https://github.com/primefaces/primeicons/issues/215 as its a duplicate of this ticket.

**Comment by Vseslavr** [comment] 2021-02-21 23:33
Duplicate of #215

**Closed** 2021-02-21 23:33 UTC
Labels: new icon
