### ISSUE TITLE
Icon request -- Icons for bold, italic, and other styles, similar to the Google Docs toolbars

### ISSUE THREAD

**Issue by anuEGq** [primefaces/primeicons#1085] opened 2024-01-19 09:44 UTC
Icons for bold, italic, and other styles, similar to the Google Docs toolbars, please

**Comment by jepsar** [comment] 2024-01-19 10:41
Duplicate of #166

**Comment by onursenture** [comment] 2024-03-09 20:17
> Duplicate of #166

+1

**Closed by onursenture** 2024-03-09 20:17 UTC
Labels: duplicate
