### ISSUE TITLE
Add "rosette" or "trophy" icon

### ISSUE THREAD

**Issue by jepsar** [primefaces/primeicons#629] opened 2022-03-28 09:37 UTC
![rosette](https://user-images.githubusercontent.com/7500178/160370512-5d644d5e-13ed-4e86-a52e-21697331d6ff.jpeg)

![trophy](https://user-images.githubusercontent.com/7500178/160370517-e76ce092-8931-4ddd-940c-4aaae575152d.jpeg)

**Comment by onursenture** [comment] 2022-06-11 08:54
Duplicate of #257

**Closed by onursenture** 2022-06-11 08:54 UTC
