### ISSUE TITLE
add new icon bus

### ISSUE THREAD

**Issue by ninelbarboza** [primefaces/primeicons#1031] opened 2023-10-13 16:40 UTC
plis add new icon bus
![bus](https://github.com/primefaces/primeicons/assets/147854667/6d20d375-0f2e-4f34-a971-2221916bfd1e)

**Comment by jepsar** [comment] 2023-10-13 16:55
Duplicate of #674

**Comment by onursenture** [comment] 2024-03-09 19:34
> Duplicate of #674

+1

**Closed by onursenture** 2024-03-09 19:34 UTC
Labels: duplicate
