### ISSUE TITLE
Thumb tack/Pin Icon

### ISSUE THREAD

**Issue by bdebut01** [primefaces/primeicons#1019] opened 2023-09-15 18:49 UTC
Useful for displaying 'pinned' items in a list that are placed above others by default. Your 'star' icon could be used in a similar fashion but suggests something closer to 'favoriting' rather than just giving higher ordering priority.

**Comment by jepsar** [comment] 2023-09-15 21:09
Duplicate of #333

**Comment by onursenture** [comment] 2024-03-06 09:42
> Duplicate of #333

+1

**Closed by onursenture** 2024-03-06 09:42 UTC
Labels: duplicate
