### ISSUE TITLE
Add "calculator" icon

### ISSUE THREAD

**Issue by Wandmalfarbe** [primefaces/primeicons#542] opened 2021-11-19 14:57 UTC
I made three mockups based on the existing tablet icon. The SVG source of each icon is attached and could be used for PrimeIcons.

## Version 1

![calculator-1](https://user-images.githubusercontent.com/17237627/142642987-1380d5f6-74d3-4d4c-b3c6-315a994b7aab.png)

## Version 2

![calculator-2](https://user-images.githubusercontent.com/17237627/142643041-e980a6ee-503b-49cd-9327-5ea5ce5d5a46.png)

## Version 3

![calculator-3](https://user-images.githubusercontent.com/17237627/142643056-7be3f21d-c67a-4b64-b9e0-23416122ede8.png)

[calculator-icons-svg-source.zip](https://github.com/primefaces/primeicons/files/7571026/calculator-icons-svg-source.zip)

**Comment by Wandmalfarbe** [comment] 2021-11-19 14:59
Duplicate of #193.

**Comment by onursenture** [comment] 2022-06-10 12:52
Duplicate of #193.

**Closed by onursenture** 2022-06-10 12:52 UTC
Labels: duplicate
