### ISSUE TITLE
Add Oscars icon

### ISSUE THREAD

**Issue by rjcpereira** [primefaces/primeicons#606] opened 2022-02-18 18:55 UTC
![Screenshot 2022-02-18 at 18 50 09](https://user-images.githubusercontent.com/6094989/154744985-60d41e4f-d334-42b1-8a2e-5dd53959f9dc.png)

**Comment by onursenture** [comment] 2022-06-11 08:29
Duplicate of #257

**Closed by onursenture** 2022-06-11 08:29 UTC
