### ISSUE TITLE
Add "train" icon

### ISSUE THREAD

**Issue by messt** [primefaces/primeicons#934] opened 2023-04-19 22:35 UTC
Please add some train icons (train, rails and maybe more).

https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Atrain%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

![train_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/62994347/233214194-3e17ac28-89e5-4ff9-91b1-a07bbfb5c148.svg)

**Comment by jepsar** [comment] 2023-04-20 04:42
Duplicate of #291

**Comment by onursenture** [comment] 2023-05-02 08:42
> Duplicate of #291

+1

**Closed by onursenture** 2023-05-02 08:42 UTC
Labels: duplicate
