### ISSUE TITLE
Add "pen-to-square" icon

### ISSUE THREAD

**Issue by Soriya-Chhai** [primefaces/primeicons#621] opened 2022-03-14 06:04 UTC
Please help add new icon Edit like below
![icon_edit](https://user-images.githubusercontent.com/75420175/158114298-b6d20062-598b-43b6-8211-d9c6f5931cb2.svg)

**Comment by onursenture** [comment] 2024-03-09 20:22
Duplicate of #255

**Closed by onursenture** 2024-03-09 20:22 UTC
Labels: duplicate
