### ISSUE TITLE
Add "cake-candles" icon

### ISSUE THREAD

**Issue by jeanbaptis123** [primefaces/primeicons#737] opened 2022-08-13 16:26 UTC
Please, add one or two related to "birthday"/ "cake" / "anniversary" in my current project I managed using heroicons and that was complex and not the proper way.

**Comment by jeanbaptis123** [comment] 2022-08-13 16:29
Please, add one or two related to "birthday"/ "cake" / "anniversary" in my current project I managed using heroicons and that was complex and not the proper way.

**Comment by onursenture** [comment] 2022-09-06 11:07
Duplicate of #316

**Closed by onursenture** 2022-09-06 11:07 UTC
