### ISSUE TITLE
Add "Student" Icon

### ISSUE THREAD

**Issue by AlanBarber** [primefaces/primeicons#889] opened 2023-02-15 21:04 UTC
Would like to see something to represent a student. Either just a graduation cap or user/person with graduation cap

https://fontawesome.com/icons/graduation-cap?s=regular&f=classic

https://www.flaticon.com/free-icons/student

**Comment by onursenture** [comment] 2023-04-14 19:41
Duplicate of #703

**Closed by onursenture** 2023-04-14 19:41 UTC
Labels: duplicate
