### ISSUE TITLE
Icon request: tip icon

### ISSUE THREAD

**Issue by GabriellReis14** [primefaces/primeicons#1084] opened 2024-01-13 19:34 UTC
Can you please add a tip icon, like a 
![icons8-ideia-24](https://github.com/primefaces/primeicons/assets/69462016/73bc9eb9-84ab-4508-97c3-238c7325862e).

The name I believe it could be `pi-tip`.

Thanks

**Comment by jepsar** [comment] 2024-01-14 19:00
Duplicate of #1067

**Comment by onursenture** [comment] 2024-03-09 20:16
> Duplicate of #1067

+1

**Closed by onursenture** 2024-03-09 20:16 UTC
Labels: duplicate
