### ISSUE TITLE
add linkedin icon

### ISSUE THREAD

**Issue by MoeAlsayed** [primefaces/primeicons#390] opened 2021-04-08 18:29 UTC
Can you add please linkedin Icon

**Comment by Giles-Aiden** [comment] 2021-04-24 12:44
+1 would be helpful

**Comment by jesseM15** [comment] 2021-04-24 18:22
+1 on this

**Comment by chalermchai-wp** [comment] 2021-05-12 09:33
+1 linkedin icon

**Comment by onursenture** [comment] 2021-10-21 08:34
Duplicate of https://github.com/primefaces/primeicons/issues/308

**Closed by onursenture** 2021-10-21 08:34 UTC
