### ISSUE TITLE
add new icon paw

### ISSUE THREAD

**Issue by leidison** [primefaces/primeicons#1032] opened 2023-10-14 00:41 UTC
Please, add new icon paw:

![image](https://github.com/primefaces/primeicons/assets/9399833/07dfb42f-7f38-42e8-9954-51f028e6459b)

**Comment by jepsar** [comment] 2023-10-14 07:44
Duplicate of #610

**Comment by onursenture** [comment] 2024-03-09 19:35
> Duplicate of #610

+1

**Closed by onursenture** 2024-03-09 19:35 UTC
Labels: duplicate
