### ISSUE TITLE
woff2 support

### ISSUE THREAD

**Issue by laoshaw** [primefaces/primeicons#551] opened 2021-12-08 15:14 UTC
When I run 'vite build' under primevue I got 4 files(svg, ttf, eot, woff) and these days I really just need woff2, how to do that? having them all under dist/ is pretty large in size. is woff2 supported?

how can I use primevue with other icon libraries?

**Comment by onursenture** [comment] 2022-06-10 13:01
Duplicate of #301.

**Closed by onursenture** 2022-06-10 13:01 UTC
Labels: duplicate
