### ISSUE TITLE
Add "gauge" icon

### ISSUE THREAD

**Issue by yaswanth-TCPL** [primefaces/primeicons#691] opened 2022-06-14 09:03 UTC
![Screenshot from 2022-06-14 14-31-51](https://user-images.githubusercontent.com/103560515/173538611-e1533f18-6014-431b-9478-5f2fe59ab61e.png)

Please provide the above icon

**Comment by onursenture** [comment] 2022-09-06 10:07
Duplicate of #585

**Closed by onursenture** 2022-09-06 10:07 UTC
