### ISSUE TITLE
Add "dashboard" icon

### ISSUE THREAD

**Issue by feelthemoon** [primefaces/primeicons#526] opened 2021-11-06 13:13 UTC

**Comment by onursenture** [comment] 2022-06-09 12:40
Can you please share an example for this icon?

**Comment by feelthemoon** [comment] 2022-06-09 16:24
Something like this

https://www.svgrepo.com/svg/314838/dashboard

**Comment by ConciseConstructs** [comment] 2023-06-02 18:14
I would second a recommendation for a "Dashboard" icon.  However the example given via svgrepo.com seems very similar to and might already be accomplished by "pi-th-large", "pi-microsoft", or "pi-qrcode".

Just my opinion but I would prefer an icon which resembles a vehicle dashboard such as a car.  For example the Ionic Framework icon library has one which is called "speedometer".  In the link below just type "speed" into the icon search field for a glimpse.

Reference:
https://ionic.io/ionicons

Thanks

**Comment by onursenture** [comment] 2024-03-06 08:17
Duplicate of #585

**Closed by onursenture** 2024-03-06 08:17 UTC
Labels: duplicate
