### ISSUE TITLE
add hourglass icon

### ISSUE THREAD

**Issue by FrahOrru** [primefaces/primeicons#712] opened 2022-07-07 07:54 UTC
Hi, can you pls add an hourglass icon like this? thank you
<img width="19" alt="clessidra" src="https://user-images.githubusercontent.com/59619306/177721633-ef5dcc93-d4b3-4959-a2ad-d55029d901eb.PNG">

**Comment by onursenture** [comment] 2022-09-06 10:26
Duplicate of #491

**Closed by onursenture** 2022-09-06 10:26 UTC
