### ISSUE TITLE
Request to add more globe icon like 

### ISSUE THREAD

**Issue by suman-novelty** [primefaces/primeicons#1098] opened 2024-02-06 19:53 UTC
https://media.istockphoto.com/id/1137975660/vector/1901-m40-i030-n020-s-c12-144256648-earth-globe-icons-world-map-geography-internet-global.webp?s=2048x2048&w=is&k=20&c=oZGKkAbHlSlqKdB3fFAyvzXlqSLZr_HvYfVoa51StBI=

**Comment by jepsar** [comment] 2024-02-06 20:10
Duplicate of #900

**Comment by onursenture** [comment] 2024-03-09 19:11
> Duplicate of #900

+1

**Closed by onursenture** 2024-03-09 19:11 UTC
Labels: duplicate
